# Generated by Django 2.2 on 2020-04-22 11:52

from django.db import migrations, models
from datetime import datetime    

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('city', models.CharField(max_length=75, verbose_name='address')),
                ('dob', models.DateField(default=datetime.now(), max_length=20, verbose_name='dob')),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile Number')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Joined Time')),
                ('modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('firstname', models.CharField(max_length=50, verbose_name='Firstname')),
                ('lastname', models.CharField(max_length=50, verbose_name='Lastname')),
                ('address', models.CharField(max_length=200, verbose_name='address')),
                ('dob', models.DateField(default=datetime.now(),max_length=20, verbose_name='dob')),
                ('company', models.CharField(max_length=75, verbose_name='Company')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staff member')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is a Super user')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Joined Time')),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('is_app_user', models.BooleanField(default=False, verbose_name='App User')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Manager',
                'verbose_name_plural': 'Managers',
                'ordering': ['firstname'],
            },
        ),
    ]
