# Generated by Django 2.2 on 2020-04-22 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(max_length=20, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='dob',
            field=models.DateField(max_length=20, verbose_name='dob'),
        ),
    ]
