# Generated by Django 2.2 on 2020-04-22 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200422_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='dob',
        ),
    ]
