# Generated by Django 2.2 on 2020-04-22 14:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200422_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 14, 50, 7, 125684, tzinfo=utc), max_length=20, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 22, 14, 50, 7, 117679, tzinfo=utc), max_length=20, verbose_name='dob'),
        ),
    ]
