# Generated by Django 2.2 on 2020-04-24 11:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200422_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 11, 22, 45, 956834, tzinfo=utc), max_length=20, verbose_name='dob'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='address'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='dob',
            field=models.DateField(default=datetime.datetime(2020, 4, 24, 11, 22, 45, 949829, tzinfo=utc), max_length=20, verbose_name='dob'),
        ),
    ]
