# Generated by Django 2.2 on 2020-04-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200424_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='dob',
        ),
    ]
